apiVersion: v1
kind: Secret
metadata:
  name: fiap-fast-food-secret
  namespace: default
  labels:
    app: fiap-fast-food-app-payments
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
