name: CI - Testes e Cobertura

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Rodar testes e cobertura
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar linter
        run: npm run lint

      - name: Rodar testes
        run: npm run test

      - name: Rodar cobertura
        run: npm run test:coverage

      - name: Checar cobertura mínima
        run: |
          COVERAGE=$(npx jest --coverage --coverageReporters=text-summary | grep 'All files' | awk '{print $3}' | sed 's/%//')
          echo "Cobertura: $COVERAGE%"
          MIN_COVERAGE=70
          if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then
            echo "Cobertura abaixo do mínimo exigido ($MIN_COVERAGE%)"
            exit 1
          fi
